---
driver:
  name: vagrant
  synced_folders:
  - ["./", "/cookbook"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31

platforms:
  - name: bento/centos-6.7

suites:
  - name: dst1
    driver:
      vm_hostname: dst1.test.manasg.com
      customize:
        memory: 2048
        cpus: 2
      network:
      - ["private_network", { ip: "172.28.3.10"} ]
    run_list:
      - 'mg_perf_iptables::dst'
  - name: src1
    driver:
      vm_hostname: src1.test.manasg.com
      customize:
        memory: 2048
        cpus: 2
      network:
      - ["private_network", { ip: "172.28.3.11"} ]
    run_list:
      - 'mg_perf_iptables::src'
